<a href="https://colab.research.google.com/github/Azeezat-git/datascience/blob/main/basics/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
list2=[10,20,30,40]
np_array_list=np.array(list2)
print(np_array_list)

[10 20 30 40]


In [8]:
np_random=np.random.randint(10,100)
print(np_random)
type(np_random)

81


int

In [9]:
np_mist=np.asarray(list2)
type(np_mist)

numpy.ndarray

In [12]:
np_matrix_int=np.random.randint(10,90,(6,4))
print(np_matrix_int)

[[15 86 66 18]
 [72 60 24 18]
 [24 61 40 40]
 [58 68 73 47]
 [54 73 77 41]
 [24 13 73 36]]


In [16]:
np_zero=np.zeros((3,4))
print(np_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
np_ones=np.ones((3,4))
print(np_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
np_full=np.full((2,6),13)
print(np_full)

[[13 13 13 13 13 13]
 [13 13 13 13 13 13]]


Mathematical operations on a np array


In [21]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [24]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

# print(a)
# print(b)
print(a+b)

[[17 17 26]
 [25 27 22]
 [22 11 16]]


In [27]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 17 26]
 [25 27 22]
 [22 11 16]]
[[ -5  -9 -12]
 [ -9 -11 -10]
 [-10  -9 -16]]
[[ 66  52 133]
 [136 152  96]
 [ 96  10   0]]
[[0.54545455 0.30769231 0.36842105]
 [0.47058824 0.42105263 0.375     ]
 [0.375      0.1        0.        ]]


Array Manipulation